#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-wlan0}"

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
#[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
#    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

#------------------------------------------------------------------------
#echo "<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i>
#<span class="sr-only">Loading...</span>"


#if [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
#  echo down # full text
#  echo down # short text
#  echo \#FF0000 # color
#  exit
#fi

case $1 in
  -4)
    AF=inet ;;
  -6)
    AF=inet6 ;;
  *)
    AF=inet6? ;;
esac

# if no interface is found, use the first device with a global scope
IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^\/]+).* scope global/ && print \$1 and exit")


if [[ $QUALITY ]]; then
    echo  # full text
    echo  # short text
    if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
	notify="$QUALITY% $IPADDR"
	twmnc --content "$notify" -s 25 --pos bottom_center --fs 25 -d 700 --bg '#2f343f' --fg  '#f3f4f5'
    fi
else
    echo 
    if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
	notify="Wifi Down"
	twmnc --content "$notify" -s 25 --pos bottom_center --fs 25 -d 700 --bg '#2f343f' --fg  '#f3f4f5'
    elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
       
    fi

fi


